import jsPDF from "jspdf";
import "jspdf-autotable";

interface ServiceRecordPdfData {
  jobId: string;
  customerName: string;
  propertyAddress: string;
  applianceName: string;
  technicianName: string;
  scheduledDate: string;
  serviceRecord: {
    visual_inspection?: string;
    appliance_condition?: string;
    flue_inspection?: string;
    combustion_co2?: string;
    combustion_co?: string;
    combustion_o2?: string;
    combustion_efficiency?: string;
    appliance_safe?: boolean;
    defects_details?: string;
    work_completed?: string;
    follow_up_required?: boolean;
    next_service_due?: string;
  };
}

export function generateServiceRecordPdf(data: ServiceRecordPdfData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("BoilerTech Service Record", pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Job Reference: ${data.jobId.slice(0, 8)}`, 14, 32);
  doc.text(`Date: ${data.scheduledDate}`, pageWidth - 14, 32, { align: "right" });

  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.5);
  doc.line(14, 36, pageWidth - 14, 36);

  let y = 44;
  const addSection = (title: string, rows: [string, string][]) => {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title, 14, y);
    y += 6;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    for (const [label, value] of rows) {
      doc.text(`${label}:`, 18, y);
      doc.text(value || "N/A", 80, y);
      y += 6;
    }
    y += 4;
  };

  addSection("Job Details", [
    ["Customer", data.customerName],
    ["Property", data.propertyAddress],
    ["Appliance", data.applianceName],
    ["Technician", data.technicianName],
  ]);

  const sr = data.serviceRecord;
  addSection("Visual Inspection", [
    ["Appliance Condition", sr.appliance_condition || ""],
    ["Flue Inspection", sr.flue_inspection || ""],
    ["General Inspection", sr.visual_inspection || ""],
  ]);

  addSection("Combustion Readings", [
    ["CO2 (%)", sr.combustion_co2 || ""],
    ["CO (ppm)", sr.combustion_co || ""],
    ["O2 (%)", sr.combustion_o2 || ""],
    ["Efficiency", sr.combustion_efficiency || ""],
  ]);

  addSection("Outcome", [
    ["Appliance Safe", sr.appliance_safe ? "Yes" : "No"],
    ["Defects", sr.defects_details || "None"],
    ["Work Completed", sr.work_completed || ""],
    ["Follow-up Required", sr.follow_up_required ? "Yes" : "No"],
    ["Next Service Due", sr.next_service_due || ""],
  ]);

  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, 80, y);
  doc.setFontSize(8);
  doc.text("Customer Signature", 14, y + 5);

  doc.line(pageWidth - 80, y, pageWidth - 14, y);
  doc.text("Technician Signature", pageWidth - 80, y + 5);

  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by BoilerTech", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  doc.save(`service-record-${data.jobId.slice(0, 8)}.pdf`);
}
