import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import customersRouter from "./customers";
import propertiesRouter from "./properties";
import appliancesRouter from "./appliances";
import jobsRouter from "./jobs";
import serviceRecordsRouter from "./service-records";
import commissioningRecordsRouter from "./commissioning-records";
import heatPumpServiceRecordsRouter from "./heat-pump-service-records";
import heatPumpCommissioningRecordsRouter from "./heat-pump-commissioning-records";
import breakdownReportsRouter from "./breakdown-reports";
import oilTankInspectionsRouter from "./oil-tank-inspections";
import oilTankRiskAssessmentsRouter from "./oil-tank-risk-assessments";
import combustionAnalysisRecordsRouter from "./combustion-analysis-records";
import burnerSetupRecordsRouter from "./burner-setup-records";
import fireValveTestRecordsRouter from "./fire-valve-test-records";
import oilLineVacuumTestsRouter from "./oil-line-vacuum-tests";
import jobCompletionReportsRouter from "./job-completion-reports";
import adminRouter from "./admin";
import notesRouter from "./notes";
import filesRouter from "./files";
import signaturesRouter from "./signatures";
import searchRouter from "./search";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import platformRouter from "./platform";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import internalRouter from "./internal";
import indexnowRouter from "./indexnow";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(customersRouter);
router.use(propertiesRouter);
router.use(appliancesRouter);
router.use(jobsRouter);
router.use(serviceRecordsRouter);
router.use(commissioningRecordsRouter);
router.use(heatPumpServiceRecordsRouter);
router.use(heatPumpCommissioningRecordsRouter);
router.use(breakdownReportsRouter);
router.use(oilTankInspectionsRouter);
router.use(oilTankRiskAssessmentsRouter);
router.use(combustionAnalysisRecordsRouter);
router.use(burnerSetupRecordsRouter);
router.use(fireValveTestRecordsRouter);
router.use(oilLineVacuumTestsRouter);
router.use(jobCompletionReportsRouter);
router.use(adminRouter);
router.use(notesRouter);
router.use(filesRouter);
router.use(signaturesRouter);
router.use(searchRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(platformRouter);
router.use(billingRouter);
router.use(webhooksRouter);
router.use(internalRouter);
router.use(indexnowRouter);

export default router;
