import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import customersRouter from "./customers";
import propertiesRouter from "./properties";
import jobsRouter from "./jobs";
import serviceRecordsRouter from "./service-records";
import commissioningRecordsRouter from "./commissioning-records";
import heatPumpServiceRecordsRouter from "./heat-pump-service-records";
import heatPumpCommissioningRecordsRouter from "./heat-pump-commissioning-records";
import breakdownReportsRouter from "./breakdown-reports";
import oilTankInspectionsRouter from "./oil-tank-inspections";
import oilTankRiskAssessmentsRouter from "./oil-tank-risk-assessments";
import combustionAnalysisRecordsRouter from "./combustion-analysis-records";
import burnerSetupRecordsRouter from "./burner-setup-records";
import fireValveTestRecordsRouter from "./fire-valve-test-records";
import oilLineVacuumTestsRouter from "./oil-line-vacuum-tests";
import jobCompletionReportsRouter from "./job-completion-reports";
import templateAdminRouter from "./template-admin";
import templateAdminTemplatesRouter from "./template-admin/templates";
import adminWebsiteTemplatesRouter from "./admin-website-templates";
import superadminTemplatesRouter from "./superadmin-templates";
import superadminTemplatesManagementRouter from "./superadmin-templates-management";
import superadminTemplateImportsRouter from "./superadmin-template-imports";
import adminRouter from "./admin";
import previewRouter from "./preview";
import notesRouter from "./notes";
import filesRouter from "./files";
import signaturesRouter from "./signatures";
import searchRouter from "./search";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import platformRouter from "./platform";
import billingRouter from "./billing";
import webhooksRouter from "./webhooks";
import internalRouter from "./internal";
import indexnowRouter from "./indexnow";
import socialRouter from "./social";
import enquiriesRouter from "./enquiries";
import geocodingRouter from "./geocoding";
import emailPreviewRouter from "./email-preview";
import accountingIntegrationsRouter from "./accounting-integrations";
import stripeConnectRouter from "./stripe-connect";
import gocardlessRouter from "./gocardless";
import homepageRouter from "./homepage";
import addonsRouter from "./addons";
import portalRouter from "./portal";
import followUpsRouter from "./follow-ups";
import calendarRouter from "./calendar";
import todosRouter from "./todos";
import directoryRouter from "./directory";
import smsRouter from "./sms";
import invoicesRouter from "./invoices";
import impersonationRouter from "./impersonation";
import supportNotesRouter from "./support-notes";
import supportTicketsRouter from "./support-tickets";
import pushNotificationsRouter from "./push-notifications";
import websiteRouter from "./website";
import websiteDomainsBlogRouter from "./website-domains-blog";
import { bookingRouter, bookingPublicRouter } from "./booking";
import { reviewRequestRouter, reviewRequestPublicRouter } from "./review-requests";
import { maintenancePlansRouter, maintenancePlansPublicRouter } from "./maintenance-plans";
import { emailCampaignsRouter, emailCampaignsPublicRouter } from "./email-campaigns";
import { missedCallRouter, missedCallPublicRouter } from "./missed-call";

const router: IRouter = Router();

router.use(homepageRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(customersRouter);
router.use(propertiesRouter);
router.use(jobsRouter);
router.use(serviceRecordsRouter);
router.use(commissioningRecordsRouter);
router.use(heatPumpServiceRecordsRouter);
router.use(heatPumpCommissioningRecordsRouter);
router.use(breakdownReportsRouter);
router.use(oilTankInspectionsRouter);
router.use(oilTankRiskAssessmentsRouter);
router.use(combustionAnalysisRecordsRouter);
router.use(burnerSetupRecordsRouter);
router.use(fireValveTestRecordsRouter);
router.use(oilLineVacuumTestsRouter);
router.use(jobCompletionReportsRouter);
router.use("/template-admin", templateAdminRouter);
router.use("/templates", templateAdminTemplatesRouter); // legacy compatibility path
router.use(adminWebsiteTemplatesRouter);
router.use(superadminTemplatesRouter);
router.use(superadminTemplatesManagementRouter);
router.use(superadminTemplateImportsRouter);
router.use(adminRouter);
router.use("/preview/templates", previewRouter);
router.use(notesRouter);
router.use(filesRouter);
router.use(signaturesRouter);
router.use(searchRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(platformRouter);
router.use(billingRouter);
router.use(webhooksRouter);
router.use(internalRouter);
router.use(indexnowRouter);
router.use(socialRouter);
router.use(enquiriesRouter);
router.use(geocodingRouter);
router.use(accountingIntegrationsRouter);
router.use(stripeConnectRouter);
router.use(gocardlessRouter);

router.use(addonsRouter);
router.use(portalRouter);
router.use(followUpsRouter);
router.use(calendarRouter);
router.use(todosRouter);
router.use(directoryRouter);
router.use(smsRouter);
router.use(invoicesRouter);
router.use(impersonationRouter);
router.use(supportNotesRouter);
router.use(supportTicketsRouter);
router.use(pushNotificationsRouter);
router.use(websiteRouter);
router.use(websiteDomainsBlogRouter);
router.use(bookingRouter);
router.use(bookingPublicRouter);
router.use(reviewRequestRouter);
router.use(reviewRequestPublicRouter);
router.use(maintenancePlansRouter);
router.use(maintenancePlansPublicRouter);
router.use(emailCampaignsRouter);
router.use(emailCampaignsPublicRouter);
router.use(missedCallRouter);
router.use(missedCallPublicRouter);
if (process.env.NODE_ENV !== "production") {
  router.use(emailPreviewRouter);
}

export default router;
