/**
 * Template Package Validation Schemas
 *
 * Zod schemas for validating TWD template packages before import.
 * Schemas match the structure generated by the Storybook template system:
 *
 * templates/[slug]/template.json          - TemplateJsonSchema
 * templates/[slug]/pages/pages.json       - TemplatePagesManifestSchema
 * templates/[slug]/pages/[page].json      - TemplatePageFileSchema
 * templates/[slug]/styles/theme.json      - TemplateThemeSchema
 * templates/[slug]/cms-mapping.json       - TemplateCmsMappingSchema
 * registry/block-registry.json            - TemplateBlockRegistrySchema
 */

import { z } from 'zod';

// ============================================================================
// Template Metadata (template.json)
// ============================================================================

/**
 * Validates templates/[slug]/template.json
 * Top-level metadata about the template package.
 */
export const TemplateJsonSchema = z.object({
  id: z.string().min(1, 'Template ID is required'),
  slug: z.string().min(1, 'Template slug is required').regex(/^[a-z0-9-]+$/, 'Slug must be lowercase alphanumeric and hyphens'),
  name: z.string().min(1, 'Template name is required'),
  version: z.string().optional(),
  status: z.string().optional(),
  category: z.string().optional(),
  style: z.string().optional(),
  description: z.string().optional(),
  industries: z.array(z.string()).optional(),
  defaultPage: z.string().optional(),
  pages: z.array(z.string()).min(1, 'At least one page is required'),
  requiredBlocks: z.array(z.string()).optional(),
  source: z.record(z.unknown()).optional(),
}).strict();

export type TemplateJson = z.infer<typeof TemplateJsonSchema>;

// ============================================================================
// Pages Manifest (pages/pages.json)
// ============================================================================

/**
 * Schema for a single page entry in the pages manifest.
 */
const PagesManifestPageSchema = z.object({
  slug: z.string().min(1, 'Page slug is required'),
  title: z.string().min(1, 'Page title is required'),
  path: z.string().min(1, 'Page path is required'),
  file: z.string().min(1, 'Page file name is required'),
  blockCount: z.number().int().nonnegative('Block count must be non-negative'),
}).strict();

/**
 * Validates templates/[slug]/pages/pages.json
 * Manifest describing all pages in the template.
 */
export const TemplatePagesManifestSchema = z.object({
  template: z.string().min(1, 'Template name is required in pages manifest'),
  defaultPage: z.string().min(1, 'Default page is required in pages manifest'),
  pages: z.array(PagesManifestPageSchema).min(1, 'At least one page is required in manifest'),
}).strict();

export type TemplatePagesManifest = z.infer<typeof TemplatePagesManifestSchema>;
export type PagesManifestPage = z.infer<typeof PagesManifestPageSchema>;

// ============================================================================
// Page Files (pages/*.json)
// ============================================================================

/**
 * Schema for SEO metadata on a page.
 */
const PageSeoSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
}).passthrough();

/**
 * Schema for a single block within a page.
 */
const PageBlockSchema = z.object({
  id: z.string().min(1, 'Block ID is required'),
  type: z.string().min(1, 'Block type is required'),
  props: z.record(z.unknown()),
}).strict();

/**
 * Validates templates/[slug]/pages/[page].json
 * Individual page file with blocks and metadata.
 */
export const TemplatePageFileSchema = z.object({
  slug: z.string().min(1, 'Page slug is required'),
  title: z.string().min(1, 'Page title is required'),
  path: z.string().min(1, 'Page path is required'),
  template: z.string().optional(),
  seo: PageSeoSchema.optional(),
  blocks: z.array(PageBlockSchema).default([]),
}).strict();

export type TemplatePageFile = z.infer<typeof TemplatePageFileSchema>;
export type PageBlock = z.infer<typeof PageBlockSchema>;

// ============================================================================
// Theme (styles/theme.json)
// ============================================================================

/**
 * Validates templates/[slug]/styles/theme.json
 * Theme configuration and design tokens.
 * Allows extra keys for future flexibility.
 */
export const TemplateThemeSchema = z.object({
  slug: z.string().optional(),
  name: z.string().optional(),
  tokens: z.record(z.unknown()).optional(),
}).passthrough();

export type TemplateTheme = z.infer<typeof TemplateThemeSchema>;

// ============================================================================
// CMS Mapping (cms-mapping.json)
// ============================================================================

/**
 * Validates templates/[slug]/cms-mapping.json
 * Mapping of template elements to CMS content fields.
 * Allows extra keys for future flexibility.
 */
export const TemplateCmsMappingSchema = z.object({
  template: z.string().optional(),
  businessFields: z.record(z.unknown()).optional(),
  repeatableCollections: z.record(z.unknown()).optional(),
}).passthrough();

export type TemplateCmsMapping = z.infer<typeof TemplateCmsMappingSchema>;

// ============================================================================
// Block Registry (registry/block-registry.json)
// ============================================================================

/**
 * Schema for a single block type entry in the registry.
 */
const BlockRegistryEntrySchema = z.object({
  type: z.string().min(1, 'Block type is required'),
  label: z.string().min(1, 'Block label is required'),
  category: z.string().min(1, 'Block category is required'),
  editableFields: z.array(z.string()).default([]),
}).strict();

/**
 * Validates registry/block-registry.json
 * Registry of available block types for this template.
 */
export const TemplateBlockRegistrySchema = z.object({
  version: z.string().optional(),
  source: z.string().optional(),
  blocks: z.array(BlockRegistryEntrySchema).min(1, 'At least one block type is required in registry'),
}).strict();

export type TemplateBlockRegistry = z.infer<typeof TemplateBlockRegistrySchema>;
export type BlockRegistryEntry = z.infer<typeof BlockRegistryEntrySchema>;

// ============================================================================
// Complete Package Schema (for optional full validation)
// ============================================================================

/**
 * Composite schema for validating the entire template package structure.
 * Useful for integration tests or complete package validation.
 */
export const TemplatePackageSchema = z.object({
  template: TemplateJsonSchema,
  pagesManifest: TemplatePagesManifestSchema,
  pages: z.record(z.string(), TemplatePageFileSchema),
  theme: TemplateThemeSchema,
  cmsMapping: TemplateCmsMappingSchema,
  blockRegistry: TemplateBlockRegistrySchema,
}).strict();

export type TemplatePackage = z.infer<typeof TemplatePackageSchema>;
