-- Migration 0001: Initial schema
-- Source: migration.sql (original)
-- Run once to establish the base schema on a fresh database.
-- On existing databases this is already applied — the migration runner
-- will record it as applied without re-running it if you use --baseline.

-- !! DO NOT EDIT THIS FILE !!
-- It is a snapshot of the original migration.sql for tracking purposes.
-- See supabase/migration.sql for the full original content.

-- This migration is marked as pre-applied on existing databases via:
--   INSERT INTO schema_migrations (version) VALUES ('0001_initial_schema') ON CONFLICT DO NOTHING;
